name: Publish clang-tidy images

on:
  push:
    branches:
      - master

jobs:
  build_images:
    strategy:
      matrix:
        version: [9, 10]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      name: Checkout
      with:
        submodules: true
    - name: Docker login
      run: echo ${{ secrets.DOCKER_ACCESSTOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Docker build
      run: docker build --no-cache --build-arg version=${{ matrix.version }} -f Dockerfile -t ${{ secrets.DOCKER_REPOSITORY }}:${{ matrix.version }} .

    - name: Push latest tag
      run: |
        docker push ${{ secrets.DOCKER_REPOSITORY }}:${{ matrix.version }}
